#! /bin/sh
#
# This script sets up a brand-new FreeBSD host as the proper piece of Buildbot
# infrastructure.  See README.rst
#
# Usage: ./bootstrap

set -e

env ASSUME_ALWAYS_YES=YES pkg install ansible git

ansible-pull -U https://github.com/buildbot/buildbot-infra --ask-vault-pass local.yml
