---
- name: configure service2
  hosts: service2
  gather_facts: no
  connection: local
  become: yes
  roles:
  - role: jail
    vars:
      name: mx
      hostname: mx.buildbot.net
      internet_visible: true
  - role: jail
    vars:
      name: ns1
      hostname: ns1.buildbot.net
      internet_visible: true
  - role: jail
    vars:
      name: syslog
      hostname: syslog.buildbot.net
      internet_visible: true
  # note that the remainder here are specified the "old way", with
  # ip_address
  - role: jail
    vars:
      name: ftp
      hostname: ftp.buildbot.net
      ip_address:
      - 'lagg0|140.211.10.243'
      - 'vlan0|192.168.80.243'
  - role: jail
    vars:
      name: lists
      hostname: lists.buildbot.net
      ip_address:
      - 'lagg0|140.211.10.241'
      - 'vlan0|192.168.80.241'
  - role: jail
    vars:
      name: www
      hostname: www.buildbot.net
      ip_address:
      - 'lagg0|140.211.10.238'
      - 'vlan0|192.168.80.238'
  - role: jail
    vars:
      name: supybot
      hostname: supybot.buildbot.net
      ip_address:
      - 'lagg0|140.211.10.245'
      - 'vlan0|192.168.80.245'
