---
- name: configure vm1
  hosts: vm1
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  # Restore once jails are moved to service{1,2,3}
  # - base-servicehost
  - role: jail
    name: buildbot
    hostname: buildbot.buildbot.net
    ip_address:
    - 'lo0|{{ hosts.buildbot.lo0 }}'    # localhost, must be first
    - 'lagg0|{{ hosts.buildbot.lagg0 }}'
    - 'vlan0|{{ hosts.buildbot.vlan0 }}'
  - role: jail
    name: docs
    hostname: docs.buildbot.net
    ip_address:
    - 'lagg0|{{ hosts.docs.lagg0 }}'
    - 'vlan0|{{ hosts.docs.vlan0 }}'
  - role: jail
    name: www
    hostname: www.buildbot.net
    ip_address:
    - 'lagg0|{{ hosts.www.lagg0 }}'
    - 'vlan0|{{ hosts.www.vlan0 }}'

# vim:ts=2:sw=2:noai:nosi
