---
- name: configure vm1
  hosts: vm1
  gather_facts: no
  connection: local
  become: yes
  roles:
  - role: base
  - role: nginx-proxy-letsencrypt
    vars:
      nginx_proxy_root: "/home/{{ service_account }}/nginx-docker"
  - role: docs
    vars:
      compose_root: "/home/{{ service_account }}/docs"
  - role: www
    vars:
      compose_root: "/home/{{ service_account }}/www"
