---
- name: configure service3
  hosts: service3
  gather_facts: no
  connection: local
  become: yes
  roles:
  - role: jail
    vars:
      name: bslave1
      hostname: bslave1.int.buildbot.net
      ip_address:
        - 'vlan0|192.168.80.226'
  - role: jail
    vars:
      name: buildbot
      hostname: buildbot.buildbot.net
      ip_address:
      - 'lo0|127.0.0.239'       # localhost, must be first
      - 'lagg0|140.211.10.239'
      - 'vlan0|192.168.80.239'
  - role: jail
    vars:
      name: mysql
      hostname: mysql.int.buildbot.net
      ip_address:
      - 'vlan0|192.168.80.215'
  - role: jail
    vars:
      name: events
      hostname: events.buildbot.net
      ip_address:
      - 'lagg0|140.211.10.227'
      - 'vlan0|192.168.80.227'

# vim:ts=2:sw=2:noai:nosi
