---
- name: configure ftp
  hosts: ftp
  gather_facts: no
  connection: local
  become: yes
  vars:
    ftp_root: /data/ftp
    ftp_hostname: ftp.buildbot.net
  roles:
  - base
  - ftp
  # run a specialized SSH daemon to receive uploads from other internal hosts
  - role: ssh
    sshd_port: 2200
    listen_addresses:
      - "{{ internal_ip }}"
    extra_config: |
        Match User buildbot
            ChrootDirectory {{ ftp_root }}
            ForceCommand internal-sftp
  - role: user
    user_id: buildbot
    user_name: Buildbot Uploader
    authorized_key: |
      ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNZ3JHrBueI3OvmDTIJXMcUxyjadRYb2+44n8kBgxgU9Da6mQv2j02OH3MbOhLZoMhxqRC5GVeqmDYjcEw+vcIQ= bbinfra@bslave1.int.buildbot.net

# vim:ts=2:sw=2:noai:nosi
