# This is a playbook to be run with ansible-pull (the usage will be described
# when a particular cron task is installed).
# To deploy a particular service manually:
# * log into the target host
# * run 'ansible-playbook -i localhost local.yml -K'
---

- name: determine local host name
  hosts: all
  gather_facts: yes
  connection: local

  tasks:
  # Use this to create "special" groups that will be used to setup a particular host.
  # We use non-fqdn here so a staging/test setup could work as well.
  - name: Group hosts by name
    group_by:
      key: "{{ansible_hostname}}"
    changed_when: False

  - debug:
      var: groups
    changed_when: False
- import_playbook: "common.yml"
  vars:
      ansible_connection: "local"

# vim:ts=2:sw=2:noai:nosi
