version: '3'
services:
  nginx-proxy:
    restart: always
    image: docker.io/nginxproxy/nginx-proxy:1.6.4
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs:ro
    networks:
      - httpproxy

networks:
  httpproxy:
    name: httpproxy
