---
- name: Install ezjail
  tags: jail
  pkgng:
    name: ezjail
    state: present
  environment: "{{ proxy_env }}"

- name: enable jail networking
  lineinfile:
    dest: "/etc/rc.conf"
    line: "{{item.option}}=\"{{item.value}}\""
    regexp: "^{{item.option}}=.*"
    state: present
  with_items:
  - option: "cloned_interfaces"
    value: "{{ nat_if }} {{ internal_if }} {{ external_if }}"
  - option: "pf_rules"
    value: "{{ pf_conf }}"
  - option: "pf_enable"
    value: "YES"
  when: "nat_if is defined"

- name: pf config
  tags: jail
  template:
    src: pf.conf
    dest: "{{ pf_conf }}"
    validate: pfctl -vnf %s
  when: "nat_if is defined"

- name: Restart pf
  tags: jail
  service:
    name: pf
    state: restarted

- name: ezjail config
  tags: jail
  template:
    src: ezjail.conf
    dest: "{{ ezjail_conf_file }}"
    mode: "0644"

- name: Populate basejail
  tags: jail
  command: ezjail-admin install
  args:
    creates: "{{ ezjail_jaildir }}/{{ ezjail_base_jail }}"
  environment: "{{ proxy_env }}"

- name: Create base flavour directories
  tags: jail
  file:
    path: "{{ ezjail_jaildir }}/flavours/{{ ezjail_default_flavour }}/{{ item }}"
    state: directory
  with_items:
  - etc

- name: Set base flavour config
  tags: jail
  copy:
    dest: "{{ ezjail_jaildir }}/flavours/{{ item }}"
    src: "flavours/{{ item }}"
  with_items:
  - "{{ ezjail_default_flavour }}/etc/make.conf"
  - "{{ ezjail_default_flavour }}/etc/periodic.conf"
  - "{{ ezjail_default_flavour }}/etc/rc.conf"

- name: Enable jails
  tags: jail
  service:
    name: ezjail
    enabled: true
