version: "3"

services:
  docs:
    image: nopush/nginx-bbdocs
    build:
      context: build_run
      dockerfile: Dockerfile.run
    restart: always
    # exposes port 80
    environment:
      - VIRTUAL_HOST=docs.buildbot.net
      - CERT_NAME=buildbot.net
    networks:
      - httpproxy
    volumes:
      - ./content:/data:ro

networks:
  httpproxy:
    external: true
