---
- name: make sure we have python3
  pkgng:
    name: python3
    state: present
  environment: "{{ proxy_env }}"

- name: install system packages
  pkgng:
    name: "{{ venv_packages }}"
    state: present
  environment: "{{ proxy_env }}"

- name: create the virtual environment
  become: yes
  become_user: "{{ venv_user }}"
  pip:
    name: "{{ venv_python_packages }}"
    editable: false
    virtualenv: "{{ venv_home_dir }}/{{ venv_name }}"
    virtualenv_command: "/usr/local/bin/python3 -m venv"
  environment: "{{ proxy_env }}"
